### ISSUE TITLE
Consider writing HTTPS asset `href`s instead of `s3://`

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-tools#65]
It doesn't really make a difference, except it's simpler to load/access assets that have a HTTPS href.

Any thoughts @jessjaco?

**Comment by jessjaco** [comment]
If I were a naive user I think I would prefer https. I tried to determine why the e.g. USGS stac catalogs use s3 though. It looks like it's a best practice for requester-pays buckets: https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#requester-pays. 

I did notice the s3:// urls don't seem to work with my favorite [QGIS stac plugin](https://plugins.qgis.org/plugins/qgis_stac/), though this [might be fixed](https://github.com/stac-utils/qgis-stac-plugin/pull/218).
