### ISSUE TITLE
Need a way to specific local "root" directory for writer

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-tools#7]
Currently the writer works for relative paths, but it would be good if we can specify `/tmp/` or `./data` as the "root" directory for output files when running end-to-end testing locally.

**Comment by jessjaco** [comment]
I know I need to do some documentation, but can't you use [dep_tools.namers.LocalPath](https://github.com/digitalearthpacific/dep-tools/blob/cc16986fce69079954b0aed1deb6dab0b7c873c7/dep_tools/namers.py#L50) and pass the absolute path via `local_folder` on initiation?

**Comment by alexgleith** [comment]
I think I tried that and it didn't work. But yeah, it looks like you should be able to do that!

**Comment by jessjaco** [comment]
Ok, I'll test when I get a chance

**Comment by alexgleith** [comment]
Testing now, and it doesn't work:

```python
from dep_tools.namers import LocalPath

# Write out files
dep_path = LocalPath("s2", "mangroves", "0.0.0", datetime, local_folder="data")
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb) Cell 8 line 4
      [1](vscode-notebook-cell:/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb#X11sZmlsZQ%3D%3D?line=0) from dep_tools.namers import LocalPath
      [3](vscode-notebook-cell:/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb#X11sZmlsZQ%3D%3D?line=2) # Write out files
----> [4](vscode-notebook-cell:/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb#X11sZmlsZQ%3D%3D?line=3) dep_path = LocalPath("s2", "mangroves", "0.0.0", datetime, local_folder="data")
      [6](vscode-notebook-cell:/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb#X11sZmlsZQ%3D%3D?line=5) writer = LocalDsWriter(itempath=dep_path)
      [7](vscode-notebook-cell:/Users/alex/git/digitalearthpacific/dep-mangroves/Test_Mangroves.ipynb#X11sZmlsZQ%3D%3D?line=6) out_files = writer.write(output_data, item_id)

TypeError: LocalPath.__init__() got multiple values for argument 'local_folder'
```

**Comment by alexgleith** [comment]
Ok, it does work if you use it like this:

```python
dep_path = LocalPath(local_folder="data", sensor="s2", dataset_id="mangroves", version="0.0.0", time=datetime)
```

Which is a bit of a confusing API... but ok :-)

**Comment by alexgleith** [comment]
And using this it writes asset URLs out wrong...

> "href": "https:/deppcpublicstorage.blob.core.windows.net/output/data/dep_s2_mangroves_PG_051_2023_ndvi.tif",

This should really now be a relative path to the STAC doc if it's writing local files.

**Comment by alexgleith** [comment]
Ok, it's fine, but this code is wrong for local writing: https://github.com/digitalearthpacific/dep-tools/blob/main/dep_tools/writers.py#L67

**Comment by alexgleith** [comment]
Closing this issue, as it works, even if it's a bit clumsy.
